### ISSUE TITLE
`ramses_cc.set_zone_mode` - broken?

### ISSUE THREAD

**Issue by iMiMx** [zxdavb/ramses_cc#163]
```yaml
hallway_heating_boost_1hour:
  sequence:
    - service: ramses_cc.set_zone_mode
      data:
        entity_id: climate.hallway
        setpoint: '{{ states.input_number.hallway_heating_boost_temperature.state | float }}'
        duration: {minutes: 60}     
```

The above worked on 21.40, in 31.7 it throws an error:

```
Logger: homeassistant.components.script.hallway_heating_boost_1hour
Source: helpers/script.py:1805
Integration: Scripts (documentation, issues)
First occurred: 07:30:57 (1 occurrences)
Last logged: 07:30:57

hallway_heating_boost_1hour: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['setpoint']
```

Checking with Developer Tools -> Services it seems that the below, 'mode' is apparently no longer optional?    

```yaml
service: ramses_cc.set_zone_mode
data:
  entity_id: climate.hallway
  setpoint: 21
  duration: {minutes: 60}   
```

`"This service requires field mode, which must be provided under data:"`

mode
The permanency of the override. Optional, one of: follow_schedule, advanced_override (until next scheduled setpoint), temporary_override (see: duration and until), or permanent_override (indefinitely).

With 'mode' set it then throws another error:

```yaml
service: ramses_cc.set_zone_mode
data:
  entity_id: climate.hallway
  setpoint: 21
  mode: temporary_override
  duration: {minutes: 60}   
```

`This service requires field until, which must be provided under data:
`

But this should be 'mutually exlusive' with duration?

```
until
The end of the temporary_override. Mutually exclusive with duration.  
```

**Comment by bluediamond1984** [comment]
It seems a bug in `services.yaml`. Not every zone_mode accepts all fields, like `follow_schedule` isn't allowed to have any of them. But `duration` and `until` are declared as required.
To fix the issue change the required state to false on line 290 en 299.

**Comment by raldred** [comment]
I get a totally different error
```
Failed to call service ramses_cc/set_zone_mode. value must be one of ['follow_schedule'] for dictionary value @ data['mode']

```

**Comment by zxdavb** [comment]
related to #169

**Comment by zxdavb** [comment]
Please re-open this issue if the bug persists after release 0.41.8.

**Comment by iMiMx** [comment]
Upgraded to latest stable (0.31.7.) seems 'mode' which is apparently optional, is not optional.

```
service: ramses_cc.set_zone_mode
data:
  entity_id: climate.living_room
  setpoint: 22
  duration: {minutes: 60}  
```   

`This service requires field mode, which must be provided under data:`


```
service: ramses_cc.set_zone_mode
data:
  entity_id: climate.living_room
  setpoint: 22
  duration: {minutes: 60}     
  mode: temporary_override
```

`This service requires field until, which must be provided under data:
`

No change from the reported issue, with 0.31.7. Downgrading again to 0.21.4, last 'stable' for me.

**Comment by zxdavb** [comment]
> Upgraded to latest stable (0.31.7) seems 'mode' which is apparently optional, is not optional.

Version **0.31.11** (stable) has been released. It should address this issue.

**Comment by iMiMx** [comment]
0.31.11 - still same issue. Downgrading to 0.21.4, where the below works:

```
service: ramses_cc.set_zone_mode
data:
  entity_id: climate.living_room
  setpoint: 22
  duration:
    minutes: 60
```

Mode should be optional (it's currently not) and until should be mutually exclusive with duration (it's currently not)

**Comment by zxdavb** [comment]
This is teh call I'm using in test/dev:
```yaml
service: ramses_cc.set_zone_mode
data:
  entity_id: climate.01_123456_02
  setpoint: 21
  duration: {minutes: 60}
```
... it throws an error: `This service requires field mode, which must be provided under data:`

But to me, this is obvious that it is `mode: temporary_override`.
