### ISSUE TITLE
ramses_cc.set_system_mode eco_boost is being set for 1 hour

### ISSUE THREAD

**Issue by brucemiranda** [zxdavb/ramses_cc#169]
```yaml
service: ramses_cc.set_system_mode
data:
  mode: eco_boost
  entity_id: climate.01_078710
```
Even with no duration specified the service is being called with a duration set to 1 hour.
