### ISSUE TITLE
0.31.7: `binary_sensor.01_078710_active_fault` is not being updated

### ISSUE THREAD

**Issue by brucemiranda** [zxdavb/ramses_cc#171]
The Active Fault sensor doesn't appear to be getting updated.
`binary_sensor.01_078710_active_fault`

When looked at via the Developer Tools the various state attributes are always null/unknown
```yaml
id: "01:078710"
active_fault: null
latest_event: null
latest_fault: null
device_class: problem
friendly_name: Controller 01:078710 Active fault
```
