### ISSUE TITLE
Best practice is exactly one gateway

### ISSUE THREAD

**Issue by sciorty** [zxdavb/ramses_cc#174]
Hello,

I just updated the version of the integration from **0.21.40** -> **0.31.7**.
This was my previous configuration that worked fine for moths with an SSM-D2. Now it simply stopped, logs are no longer present on the packets.log, there simply isn't anything since the update. Already tried to reboot the host, reset the dongle etc. Waited for an entire night but no entuty has been updated/available.

```yaml
ramses_cc:
  scan_interval: 3
  serial_port: /dev/ttyACM0
  packet_log: packets.log
  advanced_features:
    send_packet: true
  ramses_rf:
    enforce_known_list: true
  orphans_hvac: [32:142858, 32:126818]
  known_list:
    32:142858 : {class: FAN} 
    32:126818:
      class: REM
      faked: true
      commands:
        away:         ' I --- 32:126818 32:142858 --:------ 22F1 003 000007'
        low:          ' I --- 32:126818 32:142858 --:------ 22F1 003 000207'
        medium:       ' I --- 32:126818 32:142858 --:------ 22F1 003 000307'
        high:         ' I --- 32:126818 32:142858 --:------ 22F1 003 000707'
        bypass_open:  ' W --- 32:126818 32:142858 --:------ 22F7 003 00C8EF'
        bypass_close: ' W --- 32:126818 32:142858 --:------ 22F7 003 0000EF'
        bypass_auto:  ' W --- 32:126818 32:142858 --:------ 22F7 003 00FFEF'
        reset_filter: ' W --- 32:126818 32:142858 --:------ 10D0 002 00FF'
```

Works again after going back to previous version
