### ISSUE TITLE
Feature request to configure temperature step size

### ISSUE THREAD

**Issue by jrb80** [zxdavb/ramses_cc#212]
The default climate entity step size is 0.1 degrees and as a result it's somewhat cumbersome when manually setting the target temperature to a round number, e.g. 20 degrees rather that 19.9 or 20.1

It's possible to manually override this behaviour through `/homeassistant/configuration.yaml` however in the interest of mainstreaming the configuration through configuration flow, perhaps it should be a global setting under the integration?

Configuration example to set step size to 0.5 degrees
```
# Evohome override temp step size
homeassistant:
  customize:
    climate.01_123456_00:
      target_temp_step: 0.5
    climate.01_123456_01:
      target_temp_step: 0.5
    climate.01_123456_02:
      target_temp_step: 0.5
    climate.01_123456_03:
      target_temp_step: 0.5
    climate.01_123456_04:
      target_temp_step: 0.5
    climate.01_123456_05:
      target_temp_step: 0.5
```
