### ISSUE TITLE
Problem with config.yaml

### ISSUE THREAD

**Issue by Kroate** [zxdavb/ramses_cc#50]
I despair. For hours I've been trying to get my configuration to work under HA. I keep getting the following error message.

```text
Invalid config for [ramses_cc]: expected a list for dictionary value @ data['ramses_cc']['known_list']. Got OrderedDict([('32:123456', OrderedDict([('class', 'FAN'), ('_note', 'Orcon HRC 400')])), ('29:123456', OrderedDict([('class', 'REM'), ('faked', True), ('commands', OrderedDict([('away', ' I --- 29:123456 32:123456 --:------ 22F1 003 000007'), ('low', ' I --- 29:123456 32:123456 --:------ 22F1 003 000107'), ('medium', ' I --- 29:123456 32:123456 --:------ 22F1 003 000207'), ('high', ' I --- 29:123456 32:123456 --:------ 22F1 003 000307'), ('auto', ' I --- 29:123456 32:123456 --:------ 22F1 003.... (See /config/configuration.yaml, line 18).
```
Here my Config from line 18

```yaml
 ramses_cc:
   serial_port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
   known_list:
     32:123456 : { class: FAN, _note: Orcon HRC 400 } 
     29:123456:
       class: REM
       faked: True
       commands:
         away:         ' I --- 29:123456 32:123456 --:------ 22F1 003 000007'
         low:          ' I --- 29:123456 32:123456 --:------ 22F1 003 000107'
         medium:       ' I --- 29:123456 32:123456 --:------ 22F1 003 000207'
         high:         ' I --- 29:123456 32:123456 --:------ 22F1 003 000307'
         auto:         ' I --- 29:123456 32:123456 --:------ 22F1 003 000407'
         auto2:        ' I --- 29:123456 32:123456 --:------ 22F1 003 000507'
         boost:        ' I --- 29:123456 32:123456 --:------ 22F1 003 000607'
         disable:      ' I --- 29:123456 32:123456 --:------ 22F1 003 000707'
         bypass_open:  ' W --- 29:123456 32:123456 --:------ 22F7 003 00C8EF'
         bypass_close: ' W --- 29:123456 32:123456 --:------ 22F7 003 0000EF'
         bypass_auto:  ' W --- 29:123456 32:123456 --:------ 22F7 003 00FFEF'
         reset_filter: ' W --- 29:123456 32:123456 --:------ 10D0 002 00FF'
       _note: based upon an Orcon 15RF 6-button remote (VMN-15LF01)`
```
