### ISSUE TITLE
0.30.2 - `use_native_ot: never` doesn't stop `RQ|3220|00`s

### ISSUE THREAD

**Issue by zxdavb** [zxdavb/ramses_cc#84]
```yaml
  ramses_rf:
    disable_discovery: false
    enforce_known_list: false
    # use_native_ot: always  # will still RQ|3EF0|00
    # use_native_ot: never  # will still RQ|3220|00RQ|3220|00
 ```

The never should stop *all* `RQ|3220` packets, including `RQ|3220|00`.
