### ISSUE TITLE
0.30.2 - schedule service call fails

### ISSUE THREAD

**Issue by zxdavb** [zxdavb/ramses_cc#87]
```
Logger: ramses_rf.protocol.message
Source: runner.py:188
First occurred: 21:54:54 (9 occurrences)
Last logged: 21:58:00

I --- 01:065252 18:131597 --:------ 0404 007 06200008290102 < Corrupt payload: Incorrect fragment length: 0x29
```

**Comment by jrb80** [comment]
Issue remains in 0.31.2

``
 "Failed to call service ramses_cc.get_zone_schedule. Unknown error"
``

**Comment by zxdavb** [comment]
This is working for me in **0.31.7**:

```yaml
service: ramses_cc.get_zone_schedule
data:
  entity_id: climate.ramses_cc_01_145038_02
```
returns:
```yaml
{{ state_attr("climate.ramses_cc_01_145038_02", "schedule") }}
```
